### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by ryanknutson** [jack3898/fakeyou.ts#239]
Tokens were recently updated and fakeyou.ts no longer works for tts. Login works fine but it fails to fetch the model.

**Comment by jack3898** [comment]
Thanks for the issue!

I have run the e2e test suite, which simulates a TTS as a user would, and it had no issues. 🤔

- Is it a model token you're referring to? Not a login token?
- If it was a login token, this package does not support API tokens, because I was never able to get one for testing.
- Otherwise have you checked the model you want to do TTS on is still available on the fakeyou website?

I am also aware fakeyou.js (another package) is 100% not working with model tokens, just going to throw one last question 🤣 this issue wasn't meant for that repo?

**Comment by jack3898** [comment]
Any updates on this @ryanknutson? 🤔
